---
# tasks file for nginx---
- name: Copy syslog-ng configuration to /etc/syslog
  hosts: syslog
  copy:
    src: syslog-ng.conf
    dest: /etc/syslog-ng

- name: Restart the service syslog-ng
  hosts: syslog
  service:
    name: syslog-ng
    state: restarted 

- name: Install rsyslog
  hosts: linux 
  yum:
    name: rsyslog
    state: present

- name: Copy rsyslog configuration for forwarding to syslog-ng
  hosts: linux
  copy:
    src: rsyslog.conf
    dest: /etc

- name: Restart service rsyslog
  hosts: linux  
  service:
    name: rsyslog
    state: restarted


# Three dots indicate the end of a YAML document
...
