---
# tasks file for nginx---
- name: Copy syslog-ng configuration to /etc/syslog
  copy:
    src: syslog-ng.conf
    dest: /etc/syslog-ng
  when: ansible_hostname == 'centos4' 

- name: Restart the service syslog-ng
  service:
    name: syslog-ng
    state: restarted 
  when: ansible_hostname == 'centos4'

- name: Install rsyslog
  yum:
    name: rsyslog
    state: present
  when: ansible_hostname != 'centos4'

- name: Copy rsyslog configuration for forwarding to syslog-ng
  copy:
    src: rsyslog.conf
    dest: /etc
  when: ansible_hostname != 'centos4'

#- name: Copy rsyslog configuration for forwarding to syslog-ng
#  copy:
#    src: 99-forward.conf
#    dest: /etc/rsyslog.d
#  when: ansible_hostname != 'centos4'

- name: Restart service rsyslog
  service:
    name: rsyslog
    state: started 
  when: ansible_hostname != 'centos4'

# Three dots indicate the end of a YAML document
...
